/*
 * 商家收银台
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.demo.yop.sdk.service.cashier.response;


import com.yeepay.demo.yop.sdk.service.cashier.model.AggregationPayLinkResponseDTO;
import com.yeepay.yop.sdk.model.BaseResponse;

public class PayLinkOrderResponse extends BaseResponse {
    private static final long serialVersionUID = 1L;

    private AggregationPayLinkResponseDTO result;

    public AggregationPayLinkResponseDTO getResult() {
        return result;
    }

    public void setResult(AggregationPayLinkResponseDTO result) {
        this.result = result;
    }

}
