/*
 * API收银台
 * API收银台包含的所有API接口
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.demo.yop.sdk.service.nccashierapi.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.apache.commons.lang3.ObjectUtils;

/**
 * UnifiedAPICashierResponseDTO
 */
public class UnifiedAPICashierResponseDTO {
    @JsonProperty("code")
    private String code = null;

    @JsonProperty("message")
    private String message = null;

    @JsonProperty("payTool")
    private String payTool = null;

    @JsonProperty("payType")
    private String payType = null;

    @JsonProperty("merchantNo")
    private String merchantNo = null;

    @JsonProperty("token")
    private String token = null;

    @JsonProperty("resultType")
    private String resultType = null;

    @JsonProperty("resultData")
    private String resultData = null;

    @JsonProperty("extParamMap")
    private String extParamMap = null;

    public UnifiedAPICashierResponseDTO code(String code) {
        this.code = code;
        return this;
    }

    /**
     * Get code
     *
     * @return code
     **/

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public UnifiedAPICashierResponseDTO message(String message) {
        this.message = message;
        return this;
    }

    /**
     * Get message
     *
     * @return message
     **/

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public UnifiedAPICashierResponseDTO payTool(String payTool) {
        this.payTool = payTool;
        return this;
    }

    /**
     * Get payTool
     *
     * @return payTool
     **/

    public String getPayTool() {
        return payTool;
    }

    public void setPayTool(String payTool) {
        this.payTool = payTool;
    }

    public UnifiedAPICashierResponseDTO payType(String payType) {
        this.payType = payType;
        return this;
    }

    /**
     * Get payType
     *
     * @return payType
     **/

    public String getPayType() {
        return payType;
    }

    public void setPayType(String payType) {
        this.payType = payType;
    }

    public UnifiedAPICashierResponseDTO merchantNo(String merchantNo) {
        this.merchantNo = merchantNo;
        return this;
    }

    /**
     * Get merchantNo
     *
     * @return merchantNo
     **/

    public String getMerchantNo() {
        return merchantNo;
    }

    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo;
    }

    public UnifiedAPICashierResponseDTO token(String token) {
        this.token = token;
        return this;
    }

    /**
     * Get token
     *
     * @return token
     **/

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public UnifiedAPICashierResponseDTO resultType(String resultType) {
        this.resultType = resultType;
        return this;
    }

    /**
     * Get resultType
     *
     * @return resultType
     **/

    public String getResultType() {
        return resultType;
    }

    public void setResultType(String resultType) {
        this.resultType = resultType;
    }

    public UnifiedAPICashierResponseDTO resultData(String resultData) {
        this.resultData = resultData;
        return this;
    }

    /**
     * Get resultData
     *
     * @return resultData
     **/

    public String getResultData() {
        return resultData;
    }

    public void setResultData(String resultData) {
        this.resultData = resultData;
    }

    public UnifiedAPICashierResponseDTO extParamMap(String extParamMap) {
        this.extParamMap = extParamMap;
        return this;
    }

    /**
     * Get extParamMap
     *
     * @return extParamMap
     **/

    public String getExtParamMap() {
        return extParamMap;
    }

    public void setExtParamMap(String extParamMap) {
        this.extParamMap = extParamMap;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UnifiedAPICashierResponseDTO unifiedAPICashierResponseDTO = (UnifiedAPICashierResponseDTO) o;
        return ObjectUtils.equals(this.code, unifiedAPICashierResponseDTO.code) &&
                ObjectUtils.equals(this.message, unifiedAPICashierResponseDTO.message) &&
                ObjectUtils.equals(this.payTool, unifiedAPICashierResponseDTO.payTool) &&
                ObjectUtils.equals(this.payType, unifiedAPICashierResponseDTO.payType) &&
                ObjectUtils.equals(this.merchantNo, unifiedAPICashierResponseDTO.merchantNo) &&
                ObjectUtils.equals(this.token, unifiedAPICashierResponseDTO.token) &&
                ObjectUtils.equals(this.resultType, unifiedAPICashierResponseDTO.resultType) &&
                ObjectUtils.equals(this.resultData, unifiedAPICashierResponseDTO.resultData) &&
                ObjectUtils.equals(this.extParamMap, unifiedAPICashierResponseDTO.extParamMap);
    }

    @Override
    public int hashCode() {
        return ObjectUtils.hashCodeMulti(code, message, payTool, payType, merchantNo, token, resultType, resultData, extParamMap);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UnifiedAPICashierResponseDTO {\n");

        sb.append("    code: ").append(toIndentedString(code)).append("\n");
        sb.append("    message: ").append(toIndentedString(message)).append("\n");
        sb.append("    payTool: ").append(toIndentedString(payTool)).append("\n");
        sb.append("    payType: ").append(toIndentedString(payType)).append("\n");
        sb.append("    merchantNo: ").append(toIndentedString(merchantNo)).append("\n");
        sb.append("    token: ").append(toIndentedString(token)).append("\n");
        sb.append("    resultType: ").append(toIndentedString(resultType)).append("\n");
        sb.append("    resultData: ").append(toIndentedString(resultData)).append("\n");
        sb.append("    extParamMap: ").append(toIndentedString(extParamMap)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

