/*
 * API收银台
 * API收银台包含的所有API接口
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.demo.yop.sdk.service.nccashierapi;

import com.yeepay.demo.yop.sdk.service.nccashierapi.request.ApiPayRequest;
import com.yeepay.demo.yop.sdk.service.nccashierapi.request.ApiPayRequestMarshaller;
import com.yeepay.demo.yop.sdk.service.nccashierapi.response.ApiPayResponse;
import com.yeepay.yop.sdk.client.*;
import com.yeepay.yop.sdk.exception.YopClientException;
import com.yeepay.yop.sdk.http.HttpResponseAnalyzerSupport;
import com.yeepay.yop.sdk.http.HttpResponseHandler;
import com.yeepay.yop.sdk.http.handler.DefaultHttpResponseHandler;
import com.yeepay.yop.sdk.model.transform.RequestMarshaller;

@javax.annotation.Generated(value = "com.yeepay.g3.core.yop.codegen.generator2.java.YopJavaClientCodegen", date = "2020-11-05T11:17:05.219+08:00[Asia/Shanghai]")
public class NccashierapiClientImpl implements NccashierapiClient {

    private final ClientHandler clientHandler;

    NccashierapiClientImpl(ClientParams clientParams) {
        this.clientHandler = new ClientHandlerImpl(new ClientHandlerParams().withClientParams(clientParams));
    }

    @Override
    public com.yeepay.demo.yop.sdk.service.nccashierapi.response.ApiPayResponse apiPay(com.yeepay.demo.yop.sdk.service.nccashierapi.request.ApiPayRequest request) throws YopClientException {
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<com.yeepay.demo.yop.sdk.service.nccashierapi.request.ApiPayRequest> requestMarshaller = ApiPayRequestMarshaller.getInstance();
        HttpResponseHandler<com.yeepay.demo.yop.sdk.service.nccashierapi.response.ApiPayResponse> responseHandler =
                new DefaultHttpResponseHandler<com.yeepay.demo.yop.sdk.service.nccashierapi.response.ApiPayResponse>(com.yeepay.demo.yop.sdk.service.nccashierapi.response.ApiPayResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<ApiPayRequest, ApiPayResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }

    @Override
    public void shutdown() {
        clientHandler.shutdown();
    }

}
