/*
 * API收银台
 * API收银台包含的所有API接口
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.demo.yop.sdk.service.nccashierapi;

import com.yeepay.demo.yop.sdk.service.nccashierapi.request.ApiPayRequest;
import com.yeepay.demo.yop.sdk.service.nccashierapi.response.ApiPayResponse;
import com.yeepay.yop.sdk.exception.YopClientException;

@javax.annotation.Generated(value = "com.yeepay.g3.core.yop.codegen.generator2.java.YopJavaClientCodegen", date = "2020-11-05T11:17:05.219+08:00[Asia/Shanghai]")
public interface NccashierapiClient {
    /**
     * 聚合API收银台
     * &lt;p&gt;API收银台统一支付接口，支持主扫支付(微信/支付宝/京东)、被扫支付(微信/支付宝/京东)、微信公众号、小程序支付、微信SDK支付&lt;/p&gt;
     *
     * @return ApiPayResponse
     * @throws YopClientException if fails to make API call
     */
    ApiPayResponse apiPay(ApiPayRequest request) throws YopClientException;

    /**
     * Shuts down this client object, releasing any resources that might be held open. This is an optional method, and
     * callers are not expected to call it, but can if they want to explicitly release any open resources. Once a client
     * has been shutdown, it should not be used to make any more requests.
     */
    void shutdown();
}
