/*
 * API收银台
 * API收银台包含的所有API接口
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.demo.yop.sdk.service.nccashierapi;


import com.yeepay.yop.sdk.auth.AuthorizationReqRegistry;
import com.yeepay.yop.sdk.auth.DefaultAuthorizationReqRegistry;
import com.yeepay.yop.sdk.client.AbstractServiceClientBuilder;
import com.yeepay.yop.sdk.client.ClientParams;

@javax.annotation.Generated(value = "com.yeepay.g3.core.yop.codegen.generator2.java.YopJavaClientCodegen", date = "2020-11-05T11:17:05.219+08:00[Asia/Shanghai]")
public class NccashierapiClientBuilder extends AbstractServiceClientBuilder<NccashierapiClientBuilder, NccashierapiClientImpl> {

    private static final AuthorizationReqRegistry REGISTRY;

    static {
        REGISTRY = new DefaultAuthorizationReqRegistry();
        REGISTRY.register("apiPay", "YOP-RSA2048-SHA256");
    }

    @Override
    protected AuthorizationReqRegistry authorizationReqRegistry() {
        return REGISTRY;
    }

    @Override
    protected NccashierapiClientImpl build(ClientParams params) {
        return new NccashierapiClientImpl(params);
    }

    /**
     * @return Create new instance of builder with all defaults set.
     */
    public static NccashierapiClientBuilder builder() {
        return new NccashierapiClientBuilder();
    }

}
