/*
 * 商家收银台
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.demo.yop.sdk.service.cashier;

import com.yeepay.demo.yop.sdk.service.cashier.request.PayLinkOrderRequest;
import com.yeepay.demo.yop.sdk.service.cashier.response.PayLinkOrderResponse;
import com.yeepay.yop.sdk.exception.YopClientException;

@javax.annotation.Generated(value = "com.yeepay.g3.core.yop.codegen.generator2.java.YopJavaClientCodegen", date = "2020-11-05T11:17:05.732+08:00[Asia/Shanghai]")
public interface CashierClient {

    /**
     * 生成聚合订单码
     *
     * @return PayLinkOrderResponse
     * @throws YopClientException if fails to make API call
     */
    PayLinkOrderResponse payLinkOrder(PayLinkOrderRequest request) throws YopClientException;

    /**
     * Shuts down this client object, releasing any resources that might be held open. This is an optional method, and
     * callers are not expected to call it, but can if they want to explicitly release any open resources. Once a client
     * has been shutdown, it should not be used to make any more requests.
     */
    void shutdown();
}
