/*
 * 商家收银台
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.demo.yop.sdk.service.cashier;

import com.yeepay.demo.yop.sdk.service.cashier.request.PayLinkOrderRequest;
import com.yeepay.demo.yop.sdk.service.cashier.request.PayLinkOrderRequestMarshaller;
import com.yeepay.demo.yop.sdk.service.cashier.response.PayLinkOrderResponse;
import com.yeepay.yop.sdk.client.*;
import com.yeepay.yop.sdk.exception.YopClientException;
import com.yeepay.yop.sdk.http.HttpResponseAnalyzerSupport;
import com.yeepay.yop.sdk.http.HttpResponseHandler;
import com.yeepay.yop.sdk.http.handler.DefaultHttpResponseHandler;
import com.yeepay.yop.sdk.model.transform.RequestMarshaller;

@javax.annotation.Generated(value = "com.yeepay.g3.core.yop.codegen.generator2.java.YopJavaClientCodegen", date = "2020-11-05T11:17:05.732+08:00[Asia/Shanghai]")
public class CashierClientImpl implements CashierClient {

    private final ClientHandler clientHandler;

    CashierClientImpl(ClientParams clientParams) {
        this.clientHandler = new ClientHandlerImpl(new ClientHandlerParams().withClientParams(clientParams));
    }

    @Override
    public PayLinkOrderResponse payLinkOrder(PayLinkOrderRequest request) throws YopClientException {
        if (request == null) {
            throw new YopClientException("request is required.");
        }
        RequestMarshaller<PayLinkOrderRequest> requestMarshaller = PayLinkOrderRequestMarshaller.getInstance();
        HttpResponseHandler<PayLinkOrderResponse> responseHandler =
                new DefaultHttpResponseHandler<PayLinkOrderResponse>(PayLinkOrderResponse.class,
                        HttpResponseAnalyzerSupport.getAnalyzerChain());

        return clientHandler.execute(new ClientExecutionParams<PayLinkOrderRequest, PayLinkOrderResponse>()
                .withInput(request)
                .withRequestMarshaller(requestMarshaller)
                .withResponseHandler(responseHandler));
    }

    @Override
    public void shutdown() {
        clientHandler.shutdown();
    }

}
