/*
 * API收银台
 * API收银台包含的所有API接口
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.demo.yop.sdk.service.nccashierapi.response;


import com.yeepay.demo.yop.sdk.service.nccashierapi.model.UnifiedAPICashierResponseDTO;
import com.yeepay.yop.sdk.model.BaseResponse;

public class ApiPayResponse extends BaseResponse {
    private static final long serialVersionUID = 1L;

    private com.yeepay.demo.yop.sdk.service.nccashierapi.model.UnifiedAPICashierResponseDTO result;

    public com.yeepay.demo.yop.sdk.service.nccashierapi.model.UnifiedAPICashierResponseDTO getResult() {
        return result;
    }

    public void setResult(UnifiedAPICashierResponseDTO result) {
        this.result = result;
    }

}
