/*
 * 标准交易
 * <p>名称（中文）：新交易下单接口<br />名称（英文，xx.war）：opr-hessian.war<br />简介：合单支付下单与标准收款内部下单接口合并<br />wiki文档地址：http://wiki.yeepay.com/pages/viewpage.action?pageId=122095805(4.新api分组相关接口规划)<br />预计项目上线时间：2020年6月9日<br />归属/拟申请的sp编码（可选）：opr<br />期望api分组编码、名称（可选）：trade(标准交易)<br />涉及的接口：申请下单、订单查询、申请退款、退款查询</p>
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.demo.yop.sdk.service.trade.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.apache.commons.lang3.ObjectUtils;

import java.math.BigDecimal;

/**
 * QueryRefundResponseDTO
 */
public class QueryRefundResponseDTO {
    @JsonProperty("code")
    private String code = null;

    @JsonProperty("message")
    private String message = null;

    @JsonProperty("parentMerchantNo")
    private String parentMerchantNo = null;

    @JsonProperty("merchantNo")
    private String merchantNo = null;

    @JsonProperty("orderId")
    private String orderId = null;

    @JsonProperty("refundRequestId")
    private String refundRequestId = null;

    @JsonProperty("uniqueOrderNo")
    private String uniqueOrderNo = null;

    @JsonProperty("uniqueRefundNo")
    private String uniqueRefundNo = null;

    @JsonProperty("refundAmount")
    private BigDecimal refundAmount = null;

    @JsonProperty("status")
    private String status = null;

    @JsonProperty("description")
    private String description = null;

    @JsonProperty("refundRequestDate")
    private String refundRequestDate = null;

    @JsonProperty("refundSuccessDate")
    private String refundSuccessDate = null;

    @JsonProperty("failReason")
    private String failReason = null;

    @JsonProperty("realRefundAmount")
    private BigDecimal realRefundAmount = null;

    public QueryRefundResponseDTO code(String code) {
        this.code = code;
        return this;
    }

    /**
     * Get code
     *
     * @return code
     **/

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public QueryRefundResponseDTO message(String message) {
        this.message = message;
        return this;
    }

    /**
     * Get message
     *
     * @return message
     **/

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public QueryRefundResponseDTO parentMerchantNo(String parentMerchantNo) {
        this.parentMerchantNo = parentMerchantNo;
        return this;
    }

    /**
     * Get parentMerchantNo
     *
     * @return parentMerchantNo
     **/

    public String getParentMerchantNo() {
        return parentMerchantNo;
    }

    public void setParentMerchantNo(String parentMerchantNo) {
        this.parentMerchantNo = parentMerchantNo;
    }

    public QueryRefundResponseDTO merchantNo(String merchantNo) {
        this.merchantNo = merchantNo;
        return this;
    }

    /**
     * Get merchantNo
     *
     * @return merchantNo
     **/

    public String getMerchantNo() {
        return merchantNo;
    }

    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo;
    }

    public QueryRefundResponseDTO orderId(String orderId) {
        this.orderId = orderId;
        return this;
    }

    /**
     * Get orderId
     *
     * @return orderId
     **/

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public QueryRefundResponseDTO refundRequestId(String refundRequestId) {
        this.refundRequestId = refundRequestId;
        return this;
    }

    /**
     * Get refundRequestId
     *
     * @return refundRequestId
     **/

    public String getRefundRequestId() {
        return refundRequestId;
    }

    public void setRefundRequestId(String refundRequestId) {
        this.refundRequestId = refundRequestId;
    }

    public QueryRefundResponseDTO uniqueOrderNo(String uniqueOrderNo) {
        this.uniqueOrderNo = uniqueOrderNo;
        return this;
    }

    /**
     * Get uniqueOrderNo
     *
     * @return uniqueOrderNo
     **/

    public String getUniqueOrderNo() {
        return uniqueOrderNo;
    }

    public void setUniqueOrderNo(String uniqueOrderNo) {
        this.uniqueOrderNo = uniqueOrderNo;
    }

    public QueryRefundResponseDTO uniqueRefundNo(String uniqueRefundNo) {
        this.uniqueRefundNo = uniqueRefundNo;
        return this;
    }

    /**
     * Get uniqueRefundNo
     *
     * @return uniqueRefundNo
     **/

    public String getUniqueRefundNo() {
        return uniqueRefundNo;
    }

    public void setUniqueRefundNo(String uniqueRefundNo) {
        this.uniqueRefundNo = uniqueRefundNo;
    }

    public QueryRefundResponseDTO refundAmount(BigDecimal refundAmount) {
        this.refundAmount = refundAmount;
        return this;
    }

    /**
     * Get refundAmount
     *
     * @return refundAmount
     **/

    public BigDecimal getRefundAmount() {
        return refundAmount;
    }

    public void setRefundAmount(BigDecimal refundAmount) {
        this.refundAmount = refundAmount;
    }

    public QueryRefundResponseDTO status(String status) {
        this.status = status;
        return this;
    }

    /**
     * Get status
     *
     * @return status
     **/

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public QueryRefundResponseDTO description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     *
     * @return description
     **/

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public QueryRefundResponseDTO refundRequestDate(String refundRequestDate) {
        this.refundRequestDate = refundRequestDate;
        return this;
    }

    /**
     * Get refundRequestDate
     *
     * @return refundRequestDate
     **/

    public String getRefundRequestDate() {
        return refundRequestDate;
    }

    public void setRefundRequestDate(String refundRequestDate) {
        this.refundRequestDate = refundRequestDate;
    }

    public QueryRefundResponseDTO refundSuccessDate(String refundSuccessDate) {
        this.refundSuccessDate = refundSuccessDate;
        return this;
    }

    /**
     * Get refundSuccessDate
     *
     * @return refundSuccessDate
     **/

    public String getRefundSuccessDate() {
        return refundSuccessDate;
    }

    public void setRefundSuccessDate(String refundSuccessDate) {
        this.refundSuccessDate = refundSuccessDate;
    }

    public QueryRefundResponseDTO failReason(String failReason) {
        this.failReason = failReason;
        return this;
    }

    /**
     * Get failReason
     *
     * @return failReason
     **/

    public String getFailReason() {
        return failReason;
    }

    public void setFailReason(String failReason) {
        this.failReason = failReason;
    }

    public QueryRefundResponseDTO realRefundAmount(BigDecimal realRefundAmount) {
        this.realRefundAmount = realRefundAmount;
        return this;
    }

    /**
     * Get realRefundAmount
     *
     * @return realRefundAmount
     **/

    public BigDecimal getRealRefundAmount() {
        return realRefundAmount;
    }

    public void setRealRefundAmount(BigDecimal realRefundAmount) {
        this.realRefundAmount = realRefundAmount;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        QueryRefundResponseDTO queryRefundResponseDTO = (QueryRefundResponseDTO) o;
        return ObjectUtils.equals(this.code, queryRefundResponseDTO.code) &&
                ObjectUtils.equals(this.message, queryRefundResponseDTO.message) &&
                ObjectUtils.equals(this.parentMerchantNo, queryRefundResponseDTO.parentMerchantNo) &&
                ObjectUtils.equals(this.merchantNo, queryRefundResponseDTO.merchantNo) &&
                ObjectUtils.equals(this.orderId, queryRefundResponseDTO.orderId) &&
                ObjectUtils.equals(this.refundRequestId, queryRefundResponseDTO.refundRequestId) &&
                ObjectUtils.equals(this.uniqueOrderNo, queryRefundResponseDTO.uniqueOrderNo) &&
                ObjectUtils.equals(this.uniqueRefundNo, queryRefundResponseDTO.uniqueRefundNo) &&
                ObjectUtils.equals(this.refundAmount, queryRefundResponseDTO.refundAmount) &&
                ObjectUtils.equals(this.status, queryRefundResponseDTO.status) &&
                ObjectUtils.equals(this.description, queryRefundResponseDTO.description) &&
                ObjectUtils.equals(this.refundRequestDate, queryRefundResponseDTO.refundRequestDate) &&
                ObjectUtils.equals(this.refundSuccessDate, queryRefundResponseDTO.refundSuccessDate) &&
                ObjectUtils.equals(this.failReason, queryRefundResponseDTO.failReason) &&
                ObjectUtils.equals(this.realRefundAmount, queryRefundResponseDTO.realRefundAmount);
    }

    @Override
    public int hashCode() {
        return ObjectUtils.hashCodeMulti(code, message, parentMerchantNo, merchantNo, orderId, refundRequestId, uniqueOrderNo, uniqueRefundNo, refundAmount, status, description, refundRequestDate, refundSuccessDate, failReason, realRefundAmount);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class QueryRefundResponseDTO {\n");

        sb.append("    code: ").append(toIndentedString(code)).append("\n");
        sb.append("    message: ").append(toIndentedString(message)).append("\n");
        sb.append("    parentMerchantNo: ").append(toIndentedString(parentMerchantNo)).append("\n");
        sb.append("    merchantNo: ").append(toIndentedString(merchantNo)).append("\n");
        sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
        sb.append("    refundRequestId: ").append(toIndentedString(refundRequestId)).append("\n");
        sb.append("    uniqueOrderNo: ").append(toIndentedString(uniqueOrderNo)).append("\n");
        sb.append("    uniqueRefundNo: ").append(toIndentedString(uniqueRefundNo)).append("\n");
        sb.append("    refundAmount: ").append(toIndentedString(refundAmount)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    refundRequestDate: ").append(toIndentedString(refundRequestDate)).append("\n");
        sb.append("    refundSuccessDate: ").append(toIndentedString(refundSuccessDate)).append("\n");
        sb.append("    failReason: ").append(toIndentedString(failReason)).append("\n");
        sb.append("    realRefundAmount: ").append(toIndentedString(realRefundAmount)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

