/*
 * 标准交易
 * <p>名称（中文）：新交易下单接口<br />名称（英文，xx.war）：opr-hessian.war<br />简介：合单支付下单与标准收款内部下单接口合并<br />wiki文档地址：http://wiki.yeepay.com/pages/viewpage.action?pageId=122095805(4.新api分组相关接口规划)<br />预计项目上线时间：2020年6月9日<br />归属/拟申请的sp编码（可选）：opr<br />期望api分组编码、名称（可选）：trade(标准交易)<br />涉及的接口：申请下单、订单查询、申请退款、退款查询</p>
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.demo.yop.sdk.service.trade.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.apache.commons.lang3.ObjectUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * YopQueryCombineOrderResDTO
 */
public class YopQueryCombineOrderResDTO {
    @JsonProperty("code")
    private String code = null;

    @JsonProperty("message")
    private String message = null;

    @JsonProperty("parentMerchantNo")
    private String parentMerchantNo = null;

    @JsonProperty("orderId")
    private String orderId = null;

    @JsonProperty("token")
    private String token = null;

    @JsonProperty("subOrderInfoList")
    private List<SubOrderInfoDTO> subOrderInfoList = null;

    @JsonProperty("payerInfo")
    private com.yeepay.demo.yop.sdk.service.trade.model.PayerInfoDTO payerInfo = null;

    public YopQueryCombineOrderResDTO code(String code) {
        this.code = code;
        return this;
    }

    /**
     * Get code
     *
     * @return code
     **/

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public YopQueryCombineOrderResDTO message(String message) {
        this.message = message;
        return this;
    }

    /**
     * Get message
     *
     * @return message
     **/

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public YopQueryCombineOrderResDTO parentMerchantNo(String parentMerchantNo) {
        this.parentMerchantNo = parentMerchantNo;
        return this;
    }

    /**
     * Get parentMerchantNo
     *
     * @return parentMerchantNo
     **/

    public String getParentMerchantNo() {
        return parentMerchantNo;
    }

    public void setParentMerchantNo(String parentMerchantNo) {
        this.parentMerchantNo = parentMerchantNo;
    }

    public YopQueryCombineOrderResDTO orderId(String orderId) {
        this.orderId = orderId;
        return this;
    }

    /**
     * Get orderId
     *
     * @return orderId
     **/

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public YopQueryCombineOrderResDTO token(String token) {
        this.token = token;
        return this;
    }

    /**
     * Get token
     *
     * @return token
     **/

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public YopQueryCombineOrderResDTO subOrderInfoList(List<SubOrderInfoDTO> subOrderInfoList) {
        this.subOrderInfoList = subOrderInfoList;
        return this;
    }

    public YopQueryCombineOrderResDTO addSubOrderInfoListItem(SubOrderInfoDTO subOrderInfoListItem) {
        if (this.subOrderInfoList == null) {
            this.subOrderInfoList = new ArrayList<>();
        }
        this.subOrderInfoList.add(subOrderInfoListItem);
        return this;
    }

    /**
     * Get subOrderInfoList
     *
     * @return subOrderInfoList
     **/

    public List<SubOrderInfoDTO> getSubOrderInfoList() {
        return subOrderInfoList;
    }

    public void setSubOrderInfoList(List<SubOrderInfoDTO> subOrderInfoList) {
        this.subOrderInfoList = subOrderInfoList;
    }

    public YopQueryCombineOrderResDTO payerInfo(com.yeepay.demo.yop.sdk.service.trade.model.PayerInfoDTO payerInfo) {
        this.payerInfo = payerInfo;
        return this;
    }

    /**
     * Get payerInfo
     *
     * @return payerInfo
     **/

    public com.yeepay.demo.yop.sdk.service.trade.model.PayerInfoDTO getPayerInfo() {
        return payerInfo;
    }

    public void setPayerInfo(PayerInfoDTO payerInfo) {
        this.payerInfo = payerInfo;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        YopQueryCombineOrderResDTO yopQueryCombineOrderResDTO = (YopQueryCombineOrderResDTO) o;
        return ObjectUtils.equals(this.code, yopQueryCombineOrderResDTO.code) &&
                ObjectUtils.equals(this.message, yopQueryCombineOrderResDTO.message) &&
                ObjectUtils.equals(this.parentMerchantNo, yopQueryCombineOrderResDTO.parentMerchantNo) &&
                ObjectUtils.equals(this.orderId, yopQueryCombineOrderResDTO.orderId) &&
                ObjectUtils.equals(this.token, yopQueryCombineOrderResDTO.token) &&
                ObjectUtils.equals(this.subOrderInfoList, yopQueryCombineOrderResDTO.subOrderInfoList) &&
                ObjectUtils.equals(this.payerInfo, yopQueryCombineOrderResDTO.payerInfo);
    }

    @Override
    public int hashCode() {
        return ObjectUtils.hashCodeMulti(code, message, parentMerchantNo, orderId, token, subOrderInfoList, payerInfo);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class YopQueryCombineOrderResDTO {\n");

        sb.append("    code: ").append(toIndentedString(code)).append("\n");
        sb.append("    message: ").append(toIndentedString(message)).append("\n");
        sb.append("    parentMerchantNo: ").append(toIndentedString(parentMerchantNo)).append("\n");
        sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
        sb.append("    token: ").append(toIndentedString(token)).append("\n");
        sb.append("    subOrderInfoList: ").append(toIndentedString(subOrderInfoList)).append("\n");
        sb.append("    payerInfo: ").append(toIndentedString(payerInfo)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

